site_name: "Ironhack Katas Training0"  # Title of the site

# Site Navigation
nav:
  - Inicio: index.md
  - Leaderboard: 
      - Leaderboard: katas/leaderboard.md  # Ensure this file exists
  - Katas:
      - Intro to Katas: katas/intro-to-katas.md  # Ensure this file exists
  - GitErrors and common solutions:
      - Git Concepts Basics: git-docu/git-basics.md  # Ensure this file exists
      - Git Errores Frecuentes en Git: git-docu/common-errors.md  # Ensure this file exists
      - Git workflows: git-docu/workflows.md  # Ensure this file exists
  - mkdocs:
      - Update docs in GitHub Pages: teacher/publication_ghpages.md  # Ensure this file exists

# Theme Configuration
theme:
  name: material
