site_name: "Ironhack Katas Training"

nav:
  - Home: index.md
  - Leaderboard: leaderboard.md
  - Uso Frecuente y Dia 0: 
    - Uso frecuente: guia_git_katas.md
    - Dia 0: dia_0_guia_git_katas.md

theme:
  name: material

extra:
  mermaid:
    enabled: true