site_name: "Ironhack Katas Training"
site_url: "https://herreradelduque.github.io/katas0924"
repo_url: "https://github.com/herreradelduque/katas0924"

# Navegación del sitio
nav:
  - Inicio: index.md
  - Katas:
      - Introducción a las Katas: katas/intro-to-katas.md
  - mkdocs:
      - Publicación en GitHub Pages: teacher/publication_ghpages.md
  - Git - Errores y Soluciones Comunes:
      - Conceptos Básicos de Git: git/conceptos_basicos.md
      - Errores Frecuentes en Git: git/errores_frecuentes.md
      - Flujos de Trabajo con Git: git/flujo_trabajo.md

# Tema y configuración
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Plugins y extensiones opcionales
plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables

# Opciones de personalización
extra_css:
  - 'styles/extra.css'
