site_name: "Ironhack Katas Training3"  # Title of the site
site_url: "https://herreradelduque.github.io/dataptmad0924_katas"  # Correct if using this repo
repo_url: "https://github.com/herreradelduque/dataptmad0924_katas"  # Correct repository URL

# Site Navigation
nav:
  - Inicio: index.md
  - Leaderboard: 
      - Leaderboard: katas/leaderboard.md  # Ensure this file exists
  - Katas:
      - Intro to Katas: katas/intro-to-katas.md  # Ensure this file exists
  - Git - Errors and common solutions:
      - Git Concepts Basics: git/git-basics.md  # Ensure this file exists
      - Git Errores Frecuentes en Git: git/common-errors.md  # Ensure this file exists
      - Git workflows: git/workflows.md  # Ensure this file exists
  - mkdocs:
      - Update docs in GitHub Pages: teacher/publication_ghpages.md  # Ensure this file exists

# Theme Configuration
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Plugins and Extensions
plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables

# Custom Styles
extra_css:
  - 'styles/extra.css'  # Ensure this path is correct
