site_name: "Ironhack Katas Training"
site_url: "https://herreradelduque.github.io/dataptmad0924_katas_docu"
repo_url: "https://github.com/herreradelduque/dataptmad0924_katas"

# Navegación del sitio
nav:
  - Inicio: index.md
  - Leaderboard: 
      - Leaderboar: katas/leaderboard.md
  - Katas:
      - Intro to Katas: katas/intro-to-katas.md
  - Git - Errors and common solutions:
      - Git Concepts Basics: git/git-basics.md
      - Git Errores Frecuentes en Git: git/common-errors.md
      - Git workflows: git/workflows.md
  - mkdocs:
      - Update docs in GitHub Pages: teacher/publication_ghpages.md

# Tema y configuración
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Plugins y extensiones opcionales
plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables

# Opciones de personalización
extra_css:
  - 'styles/extra.css'
