site_name: "Ironhack Katas Training0"

nav:
  - Inicio: index.md
  - Leaderboard: 
      - Leaderboard: katas/leaderboard.md
  - Katas:
      - Intro to Katas: katas/intro-to-katas.md
  - GitErrors and common solutions:
      - Git Concepts Basics: git-docu/git-basics.md
      - Git Errores Frecuentes en Git: git-docu/common-errors.md
      - Git workflows: git-docu/workflows.md
  - mkdocs:
      - Update docs in GitHub Pages: teacher/publication_ghpages.md

theme:
  name: material
