name: Update Merge Leaderboard with Python

on:
  pull_request:
    types: [closed]

jobs:
  update_leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Generate Merge Leaderboard
        env:
          STUDENT_EMAIL_MAP: ${{ secrets.STUDENT_EMAIL_MAP }}  # Importamos el secret
        run: |
          # Ejecutar script Python para actualizar el leaderboard
          python3 -c "
import json
import os

# Obtener datos del secret
STUDENT_EMAIL_MAP = json.loads(os.environ['STUDENT_EMAIL_MAP'])

# Leer pr_stats.json
with open('pr_stats.json', 'r') as f:
    stats = json.load(f)

# Buscar al usuario con más merges
leader = None
max_merges = 0

for user, data in stats['users'].items():
    if data['merge_count'] > max_merges:
        leader = user
        max_merges = data['merge_count']

# Obtener nombre real del secret
leader_name = STUDENT_EMAIL_MAP.get(leader, [None, leader])[1]  # Nombre real o username si no existe

# Crear leaderboard.md
with open('leaderboard.md', 'w') as f:
    f.write(f'## Ranking de PR Mergeados\\n\\n')
    f.write(f'El es
