name: PR-Count Update Merge Leaderboard with Python

on:
  pull_request:
    types: [closed]

jobs:
  update_leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure the full history is fetched, so we can push back to the branch

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip

      - name: Generate Merge Leaderboard
        env:
          STUDENT_EMAIL_MAP: ${{ secrets.STUDENT_EMAIL_MAP }}  # Importamos el secret
        run: |
          python3 generate_leaderboard.py

      - name: Commit and push updated leaderboard
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add leaderboard.md
          git commit -m "Update merge leaderboard"
          git push origin HEAD:${{ github.ref }}
