name: Notify on PR Creation

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  notify_pr_creation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Get PR author
      id: get_pr_author
      run: |
        PR_AUTHOR="${{ github.event.pull_request.user.login }}"
        echo "PR author: $PR_AUTHOR"
        echo "pr_author=$PR_AUTHOR" >> $GITHUB_ENV

    - name: Send PR creation email
      run: |
        python src/scripts/send_email_notification.py --event "pr_created"
      env:
        STUDENT_USERNAME: ${{ env.pr_author }}
        PR_LINK: ${{ github.event.pull_request.html_url }}
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        STUDENT_EMAIL_MAP: ${{ secrets.STUDENT_EMAIL_MAP }}
        LESSONS_URL: "https://account.ironhack.com/auth/realms/students/protocol/openid-connect/auth?client_id=student-portal&redirect_uri=https%3A%2F%2Fmy.ironhack.com%2Fjobs&state=fb7adf75-d676-43fd-aa3a-add8b7de54bd&response_mode=fragment&response_type=code&scope=openid&nonce=2fad9690-3368-46bc-95cd-965d38186efc"
