name: PR Count Workflow

on:
  pull_request:
    types: [closed]

jobs:
  count_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install requests module

      - name: Run PR Count Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token secret
          GITHUB_REPOSITORY: ${{ github.repository }}  # Get the repo name
        run: |
          python3 src/scripts/pr-count.py  # Adjust the path as necessary

      - name: Commit and push updated stats
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add pr_stats.json
          git commit -m "Update PR stats"
          git push origin HEAD:main  # Push to main branch
