name: PR-Count

on:
  pull_request:
    types: [closed]

jobs:
  update_leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/scripts/requirements.txt
        
      - name: List installed packages
        run: |
          pip list
        
      - name: Run PR Count Script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Ensure the correct token is referenced
        run: |
          python3 src/scripts/pr-count.py

      - name: Commit and push updated stats
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add src/scripts/pr_stats.json leaderboard.md
          git commit -m "Update PR stats and leaderboard" || echo "No changes to commit"
          git pull origin main --rebase
          git push origin main
