name: Notify Students on PR Submission

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Send notification to student
      run: |
        pip install requests
        python scripts/send_email_notification2.py
    
        STUDENT_EMAIL: ${{ github.event.pull_request.user.email }}  # Correo del autor de la PR
        PR_LINK: ${{ github.event.pull_request.html_url }}  # Enlace a la PR
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Secreto de autenticaci칩n
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}  # Correo electr칩nico del remitente
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}  # Contrase침a de aplicaci칩n
